name: SmartChemist
channels:
  - https://conda.anaconda.org/conda-forge/
  - defaults
  - conda-forge
dependencies:
  - rdkit
  - anaconda::redis
  - conda-forge::celery
  - conda-forge::djangorestframework
  - conda-forge::gunicorn
  - conda-forge::drf-spectacular
